In [1]:
import numpy as np
import pandas as pd

In [2]:
books=pd.read_csv("Desktop/Books.csv")
users=pd.read_csv("Desktop/Users.csv")
ratings=pd.read_csv("Desktop/Ratings.csv")

C:\Users\Dell\AppData\Local\Temp\ipykernel_14804\1139355198.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books=pd.read_csv("Desktop/Books.csv")

In [3]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
books.shape

(271360, 8)

In [5]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [6]:
users.shape

(278858, 3)

In [7]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [8]:
ratings.shape

(1149780, 3)

In [9]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [10]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [11]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [12]:
books.duplicated().sum()

0

In [13]:
users.duplicated().sum()

0

In [14]:
ratings.duplicated().sum()

0

## Popularity Based Recommendation System

In [15]:
ratings_with_name=ratings.merge(books,on='ISBN')

In [16]:
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276704,0876044011,0,Edgar Cayce on the Akashic Records: The Book o...,Kevin J. Todeschi,1998,A.R.E. Press (Association of Research &amp; Enlig,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...
1031132,276704,1563526298,9,Get Clark Smart : The Ultimate Guide for the S...,Clark Howard,2000,Longstreet Press,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...
1031133,276706,0679447156,0,Eight Weeks to Optimum Health: A Proven Progra...,Andrew Weil,1997,Alfred A. Knopf,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...
1031134,276709,0515107662,10,The Sherbrooke Bride (Bride Trilogy (Paperback)),Catherine Coulter,1996,Jove Books,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...
1031135,276721,0590442449,10,Fourth Grade Rats,Jerry Spinelli,1996,Scholastic,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...

In [17]:
num_ratings=ratings_with_name.groupby("Book-Title").count()["Book-Rating"].reset_index()
num_ratings

                                               Book-Title  Book-Rating
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [18]:
num_ratings.rename(columns={'Book-Rating':'No. of Book Ratings'},inplace=True)

In [19]:
num_ratings

                                               Book-Title  No. of Book Ratings
0        A Light in the Storm: The Civil War Diary of ...                    4
1                                   Always Have Popsicles                    1
2                    Apple Magic (The Collector's series)                    1
3        Ask Lily (Young Women of Faith: Lily Series, ...                    1
4        Beyond IBM: Leadership Marketing and Finance ...                    1
...                                                   ...                  ...
241066                                      Ã?Â?lpiraten.                    2
241067                     Ã?Â?rger mit Produkt X. Roman.                    4
241068                                Ã?Â?sterlich leben.                    1
241069                              Ã?Â?stlich der Berge.                    3
241070                                  Ã?Â?thique en toc                    2

[241071 rows x 2 columns]

In [20]:
avg_ratings=ratings_with_name.groupby('Book-Title')['Book-Rating'].mean().reset_index()

In [21]:
avg_ratings

                                               Book-Title  Book-Rating
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [22]:
avg_ratings.rename(columns={"Book-Rating":"Avg Rating"},inplace=True)

In [23]:
avg_ratings

                                               Book-Title  Avg Rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [24]:
popular_df=pd.merge(num_ratings,avg_ratings,on="Book-Title",how="inner")

In [25]:
popular_df[popular_df['No. of Book Ratings']>=250]

,Book-Title,No. of Book Ratings,Avg Rating
764,1984,284,4.454225
818,1st to Die: A Novel,509,3.575639
1048,2nd Chance,356,3.269663
1760,A Bend in the Road,346,3.364162
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
...,...,...,...
233850,White Oleander : A Novel,387,3.506460
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472
234740,Wicked: The Life and Times of the Wicked Witch...,326,3.766871
234951,Wild Animus,2502,1.019584
240860,"\O\"" Is for Outlaw""",269,2.988848

In [26]:
# Top 50 Popular Books

In [27]:
popular_df=popular_df[popular_df["No. of Book Ratings"]>=250].sort_values("Avg Rating",ascending=False).head(50)

In [28]:
popular_df

,Book-Title,No. of Book Ratings,Avg Rating
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
764,1984,284,4.454225
144165,Prodigal Summer: A Novel,253,4.450593
128670,Neverwhere,265,4.449057
206502,The Secret Life of Bees,774,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
191589,The Hitchhiker's Guide to the Galaxy,268,4.328358
129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
93381,Into the Wild,252,4.273810
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
136145,Outlander,283,4.173145
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
156102,Seabiscuit: An American Legend,275,4.098182
107962,Life of Pi,664,4.088855
176845,The Bean Trees,389,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
8434,ANGELA'S ASHES,279,4.075269
76343,Good in Bed,490,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
12700,American Gods,302,4.006623
161645,Skipping Christmas,322,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000
181679,The Color Purple,314,3.964968
160336,Silence of the Lambs,256,3.960938
8752,About a Boy,262,3.900763
158138,Seven Up (A Stephanie Plum Novel),278,3.888489
175097,The Alchemist: A Fable About Following Your Dream,266,3.875940
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279
170101,Suzanne's Diary for Nicholas,457,3.820569
111073,Lord of the Flies,259,3.818533
5664,A Prayer for Owen Meany,413,3.796610
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472

In [29]:
popular_df=popular_df.merge(books,on='Book-Title').drop_duplicates("Book-Title")[['Book-Title','Book-Author','Publisher','No. of Book Ratings','Avg Rating']]

In [30]:
popular_df

,Book-Title,Book-Author,Publisher,No. of Book Ratings,Avg Rating
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,Scholastic,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,Scholastic,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,Scholastic,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,Scholastic,347,5.501441
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,Scholastic,556,5.183453
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,Del Rey,281,5.007117
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,Del Rey,368,4.948370
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,Arthur A. Levine Books,575,4.895652
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,Del Rey,260,4.880769
39,To Kill a Mockingbird,Harper Lee,Little Brown &amp; Company,510,4.700000
47,The Da Vinci Code,Dan Brown,Doubleday,898,4.642539
53,The Five People You Meet in Heaven,Mitch Albom,Hyperion,430,4.551163
55,The Catcher in the Rye,J.D. Salinger,"Little, Brown",449,4.545657
62,The Lovely Bones: A Novel,Alice Sebold,"Little, Brown",1295,4.468726
63,1984,George Orwell,Signet Book,284,4.454225
72,Prodigal Summer: A Novel,Barbara Kingsolver,Perennial,253,4.450593
73,Neverwhere,Neil Gaiman,Avon,265,4.449057
78,The Secret Life of Bees,Sue Monk Kidd,Penguin Books,774,4.447028
84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,Regan Books,283,4.356890
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,Doubleday,493,4.354970
88,The Red Tent (Bestselling Backlist),Anita Diamant,Picador USA,723,4.334716
89,The Hitchhiker's Guide to the Galaxy,Douglas Adams,Pocket,268,4.328358
98,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,Owl Books,335,4.289552
100,Into the Wild,Jon Krakauer,Anchor,252,4.273810
103,Fahrenheit 451,Ray Bradbury,Distribooks Inc,409,4.264059
116,Girl with a Pearl Earring,Tracy Chevalier,Plume Books,526,4.218631
117,Outlander,DIANA GABALDON,Dell,283,4.173145
123,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,Warner Books,585,4.105983
124,Seabiscuit: An American Legend,LAURA HILLENBRAND,Ballantine Books,275,4.098182
126,Life of Pi,Yann Martel,Harcourt,664,4.088855
130,The Bean Trees,Barbara Kingsolver,Perennial,389,4.087404
133,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,Health Communications,265,4.086792
135,ANGELA'S ASHES,Frank McCourt,Scribner,279,4.075269
137,Good in Bed,Jennifer Weiner,Washington Square Press,490,4.055102
139,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,Perennial,321,4.037383
140,American Gods,Neil Gaiman,HarperTorch,302,4.006623
141,Skipping Christmas,JOHN GRISHAM,Doubleday,322,4.006211
147,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,Tyndale House Publishers,318,4.003145
149,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,Knopf Books for Young Readers,336,4.000000
157,The Color Purple,Alice Walker,Pocket Books,314,3.964968
163,Silence of the Lambs,Thomas Harris,St. Martin's Press,256,3.960938
166,About a Boy,Nick Hornby,Riverhead Books,262,3.900763
173,Seven Up (A Stephanie Plum Novel),Janet Evanovich,St. Martin's Press,278,3.888489
175,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,HarperSanFrancisco,266,3.875940
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,St. Martin's Paperbacks,269,3.825279
182,Suzanne's Diary for Nicholas,James Patterson,"Little, Brown",457,3.820569
186,Lord of the Flies,William Gerald Golding,Perigee Trade,259,3.818533
192,A Prayer for Owen Meany,John Irving,Ballantine Books,413,3.796610
194,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,Ballantine Books,301,3.777409
195,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,Back Bay Books,356,3.772472

## Collaborative Filtering Based Recommendation System

In [31]:
x=ratings_with_name.groupby("User-ID").count()["Book-Rating"]>200

In [32]:
df=x[x].reset_index()

In [33]:
df

     User-ID  Book-Rating
0        254         True
1       2276         True
2       2766         True
3       2977         True
4       3363         True
..       ...          ...
806   274308         True
807   275970         True
808   277427         True
809   277639         True
810   278418         True

[811 rows x 2 columns]

In [34]:
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276704,0876044011,0,Edgar Cayce on the Akashic Records: The Book o...,Kevin J. Todeschi,1998,A.R.E. Press (Association of Research &amp; Enlig,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...
1031132,276704,1563526298,9,Get Clark Smart : The Ultimate Guide for the S...,Clark Howard,2000,Longstreet Press,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...
1031133,276706,0679447156,0,Eight Weeks to Optimum Health: A Proven Progra...,Andrew Weil,1997,Alfred A. Knopf,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...
1031134,276709,0515107662,10,The Sherbrooke Bride (Bride Trilogy (Paperback)),Catherine Coulter,1996,Jove Books,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...
1031135,276721,0590442449,10,Fourth Grade Rats,Jerry Spinelli,1996,Scholastic,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...

In [35]:
filtered=pd.merge(df,ratings_with_name,on="User-ID",how="inner")

In [36]:
filtered.drop("Book-Rating_x",axis=1,inplace=True)

In [37]:
filtered

,User-ID,ISBN,Book-Rating_y,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,254,006000438X,0,The Death of Vishnu: A Novel,Manil Suri,2002,Perennial,http://images.amazon.com/images/P/006000438X.0...,http://images.amazon.com/images/P/006000438X.0...,http://images.amazon.com/images/P/006000438X.0...
1,254,0060013117,0,Night Watch,Terry Pratchett,2002,HarperCollins,http://images.amazon.com/images/P/0060013117.0...,http://images.amazon.com/images/P/0060013117.0...,http://images.amazon.com/images/P/0060013117.0...
2,254,0060199563,0,Thief of Time,Terry Pratchett,2001,HarperCollins Publishers,http://images.amazon.com/images/P/0060199563.0...,http://images.amazon.com/images/P/0060199563.0...,http://images.amazon.com/images/P/0060199563.0...
3,254,0060391448,0,Wicked : The Life and Times of the Wicked Witc...,Gregory Maguire,1995,HarperCollins,http://images.amazon.com/images/P/0060391448.0...,http://images.amazon.com/images/P/0060391448.0...,http://images.amazon.com/images/P/0060391448.0...
4,254,0060502320,7,"I've Got You, Babe",Karen Kendall,2002,Avon,http://images.amazon.com/images/P/0060502320.0...,http://images.amazon.com/images/P/0060502320.0...,http://images.amazon.com/images/P/0060502320.0...
...,...,...,...,...,...,...,...,...,...,...
474002,278418,1885222971,0,The Lion King: The Pal Patrol (Disney's \Story...,Inc. Staff Disney Enterprises,1997,Advance Publishers LLC,http://images.amazon.com/images/P/1885222971.0...,http://images.amazon.com/images/P/1885222971.0...,http://images.amazon.com/images/P/1885222971.0...
474003,278418,188522298X,0,101 Dalmatians: Proud to Be a Pup,Disney Enterprises Inc,1997,Advance Publishers LLC,http://images.amazon.com/images/P/188522298X.0...,http://images.amazon.com/images/P/188522298X.0...,http://images.amazon.com/images/P/188522298X.0...
474004,278418,1885222998,0,Aladdin: Wishful Thinking (Disney's Storytime ...,Disney Enterprises Inc,1997,Advance Publishers LLC,http://images.amazon.com/images/P/1885222998.0...,http://images.amazon.com/images/P/1885222998.0...,http://images.amazon.com/images/P/1885222998.0...
474005,278418,1892083043,0,Gotcha! Strategy Games for Math and Logic (Hom...,Denise Gaskins,1998,Tabletop Academy Pr,http://images.amazon.com/images/P/1892083043.0...,http://images.amazon.com/images/P/1892083043.0...,http://images.amazon.com/images/P/1892083043.0...
474006,278418,1931102589,0,Science Fiction Classics (8 Cassette Deluxe Ed...,H.G. Wells,2001,Topics Entertainment,http://images.amazon.com/images/P/1931102589.0...,http://images.amazon.com/images/P/1931102589.0...,http://images.amazon.com/images/P/1931102589.0...

In [38]:
y=filtered.groupby("Book-Title").count()["Book-Rating_y"]>=50

In [39]:
DF=y[y].reset_index()

In [40]:
DF

                                            Book-Title  Book-Rating_y
0                                                 1984           True
1                                  1st to Die: A Novel           True
2                                           2nd Chance           True
3                                            4 Blondes           True
4                                   A Bend in the Road           True
..                                                 ...            ...
701                                    Year of Wonders           True
702                                   You Belong To Me           True
703  Zen and the Art of Motorcycle Maintenance: An ...           True
704                                               Zoya           True
705                                \O\" Is for Outlaw"           True

[706 rows x 2 columns]

In [41]:
final_ratings=pd.merge(filtered,DF,on="Book-Title",how="inner")

In [42]:
final_ratings

,User-ID,ISBN,Book-Rating_y_x,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Book-Rating_y_y
0,254,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...,True
1,254,0062502174,0,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,1993,HarperSanFrancisco,http://images.amazon.com/images/P/0062502174.0...,http://images.amazon.com/images/P/0062502174.0...,http://images.amazon.com/images/P/0062502174.0...,True
2,254,014028009X,0,Bridget Jones's Diary,Helen Fielding,1999,Penguin Books,http://images.amazon.com/images/P/014028009X.0...,http://images.amazon.com/images/P/014028009X.0...,http://images.amazon.com/images/P/014028009X.0...,True
3,254,0140298479,0,Bridget Jones: The Edge of Reason,Helen Fielding,2001,Penguin Books,http://images.amazon.com/images/P/0140298479.0...,http://images.amazon.com/images/P/0140298479.0...,http://images.amazon.com/images/P/0140298479.0...,True
4,254,014100018X,0,Chocolat,Joanne Harris,2000,Penguin Books,http://images.amazon.com/images/P/014100018X.0...,http://images.amazon.com/images/P/014100018X.0...,http://images.amazon.com/images/P/014100018X.0...,True
...,...,...,...,...,...,...,...,...,...,...,...
58581,278418,0786817070,0,"Artemis Fowl (Artemis Fowl, Book 1)",Eoin Colfer,2002,Miramax Kids,http://images.amazon.com/images/P/0786817070.0...,http://images.amazon.com/images/P/0786817070.0...,http://images.amazon.com/images/P/0786817070.0...,True
58582,278418,0786889020,0,Don't Stand Too Close to a Naked Man,Tim Allen,1995,Hyperion,http://images.amazon.com/images/P/0786889020.0...,http://images.amazon.com/images/P/0786889020.0...,http://images.amazon.com/images/P/0786889020.0...,True
58583,278418,080410526X,0,All I Really Need to Know,ROBERT FULGHUM,1989,Ivy Books,http://images.amazon.com/images/P/080410526X.0...,http://images.amazon.com/images/P/080410526X.0...,http://images.amazon.com/images/P/080410526X.0...,True
58584,278418,0821759744,0,Dangerous,Becky Barker,1997,Kensington Publishing Corporation,http://images.amazon.com/images/P/0821759744.0...,http://images.amazon.com/images/P/0821759744.0...,http://images.amazon.com/images/P/0821759744.0...,True
58585,278418,1559029838,0,Call of the Wild,Jack London,0,Selldowns/no More Orders,http://images.amazon.com/images/P/1559029838.0...,http://images.amazon.com/images/P/1559029838.0...,http://images.amazon.com/images/P/1559029838.0...,True

In [43]:
final_ratings.drop("Book-Rating_y_y",axis=1,inplace=True)

In [44]:
final_ratings.rename(columns={"Book-Rating_y_x":"Book-Rating"},inplace=True)

In [45]:
final_ratings

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,254,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...
1,254,0062502174,0,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,1993,HarperSanFrancisco,http://images.amazon.com/images/P/0062502174.0...,http://images.amazon.com/images/P/0062502174.0...,http://images.amazon.com/images/P/0062502174.0...
2,254,014028009X,0,Bridget Jones's Diary,Helen Fielding,1999,Penguin Books,http://images.amazon.com/images/P/014028009X.0...,http://images.amazon.com/images/P/014028009X.0...,http://images.amazon.com/images/P/014028009X.0...
3,254,0140298479,0,Bridget Jones: The Edge of Reason,Helen Fielding,2001,Penguin Books,http://images.amazon.com/images/P/0140298479.0...,http://images.amazon.com/images/P/0140298479.0...,http://images.amazon.com/images/P/0140298479.0...
4,254,014100018X,0,Chocolat,Joanne Harris,2000,Penguin Books,http://images.amazon.com/images/P/014100018X.0...,http://images.amazon.com/images/P/014100018X.0...,http://images.amazon.com/images/P/014100018X.0...
...,...,...,...,...,...,...,...,...,...,...
58581,278418,0786817070,0,"Artemis Fowl (Artemis Fowl, Book 1)",Eoin Colfer,2002,Miramax Kids,http://images.amazon.com/images/P/0786817070.0...,http://images.amazon.com/images/P/0786817070.0...,http://images.amazon.com/images/P/0786817070.0...
58582,278418,0786889020,0,Don't Stand Too Close to a Naked Man,Tim Allen,1995,Hyperion,http://images.amazon.com/images/P/0786889020.0...,http://images.amazon.com/images/P/0786889020.0...,http://images.amazon.com/images/P/0786889020.0...
58583,278418,080410526X,0,All I Really Need to Know,ROBERT FULGHUM,1989,Ivy Books,http://images.amazon.com/images/P/080410526X.0...,http://images.amazon.com/images/P/080410526X.0...,http://images.amazon.com/images/P/080410526X.0...
58584,278418,0821759744,0,Dangerous,Becky Barker,1997,Kensington Publishing Corporation,http://images.amazon.com/images/P/0821759744.0...,http://images.amazon.com/images/P/0821759744.0...,http://images.amazon.com/images/P/0821759744.0...
58585,278418,1559029838,0,Call of the Wild,Jack London,0,Selldowns/no More Orders,http://images.amazon.com/images/P/1559029838.0...,http://images.amazon.com/images/P/1559029838.0...,http://images.amazon.com/images/P/1559029838.0...

In [46]:
pt=final_ratings.pivot_table(index="Book-Title",columns="User-ID",values="Book-Rating")

In [47]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,9.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN

In [48]:
pt.fillna(0,inplace=True)

In [49]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

In [51]:
similarity_scores=cosine_similarity(pt)

In [52]:
similarity_scores.shape

(706, 706)

In [53]:
def recommend(book_name):
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:5]
    data = []
    for i in similar_items:
        item = []
        temp_df = books[books['Book-Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        data.append(item)
    return data

In [54]:
recommend('1984')

[['Animal Farm',
  'George Orwell',
  'http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg'],
 ["The Handmaid's Tale",
  'Margaret Atwood',
  'http://images.amazon.com/images/P/0449212602.01.MZZZZZZZ.jpg'],
 ['Brave New World',
  'Aldous Huxley',
  'http://images.amazon.com/images/P/0060809833.01.MZZZZZZZ.jpg'],
 ['The Vampire Lestat (Vampire Chronicles, Book II)',
  'ANNE RICE',
  'http://images.amazon.com/images/P/0345313860.01.MZZZZZZZ.jpg']]

In [55]:
pt.index[545]

"The Handmaid's Tale"